### PR TITLE
Checkbox fixed and reviewed console.logs

### LINKED ISSUE #51: Make sure spreadsheet data overrides postgres data
If something is checked on the spreadsheet and gets unchecked in our app, on refresh, it should be checked again on the view of that order. (for pickup)

### LINKED ISSUE #52: Checkbox values disappear if table is re-rendered (sorted/filtered)
Currently if a checkbox value is changed and the table is re-rendered by sorting or filtering, the updated value is not present. This is due to the fact that you are changing the internal state of the checkbox but not the actual data. You will have to use a callback function.

### LINKED ISSUE #64: Cleanup logs in server

### PR DESCRIPTION
**Pull request by youzhentsai**
Google sheet now overrides the local database, and checkbox changes do not require refresh.
Fixes #51 
Fixes #52 
Fixes #64

### CODE REVIEW

File: backend/app.js [hunk 1]
```diff
@@ -193,14 +193,16 @@ app.get("/orders", withAuth, function(req, res) {
...
         for (rowIndex = 0; rowIndex < rows.length; rowIndex++) {
+          var gsPickUp = rows[rowIndex][7];
           var pickUpStatus = await ordersdb.checkAgainst(
             rows[rowIndex][3],
-            rows[rowIndex][5]
+            rows[rowIndex][5],
+            rows[rowIndex][7]
           );
-          rows[rowIndex][7] = pickUpStatus;
+          rows[rowIndex][7] = { pickUpStatus, gsPickUp };
```
Comment (trev4ev) [inline backend/app.js:202]: good idea sending both values to the frontend

File: backend/orderquery.js [hunk 2]
```diff
@@ -11,13 +11,17 @@ const pool = new Pool({
...
     const result = await pool.query(
       "SELECT * FROM order_table WHERE order_number = $1 AND item = $2",
       [gsOrder, gsItem]
     );
-    return result.rows[0].picked_up;
+    if (gsPickUp) {
+      return gsPickUp;
+    } else {
+      return result.rows[0].picked_up;
+    }
```
Comment (trev4ev) [inline backend/orderquery.js]: future tip this can be condensed into `return gsPickUp || result.rows[0].picked_up` which is arguably more intuitive

File: src/components/Checkbox.js [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import React from "react";
+import Orders from "./Orders";
```
Comment (trev4ev) [inline src/components/Checkbox.js]: remove this (I don't think its necessary)

File: src/components/Orders.js [hunk 4]
```diff
@@ -39,10 +50,12 @@ class Orders extends React.Component {
         ItemQuantity: item[6],
         PickupStatus: (
           <Checkbox
-            key={item[3]}
-            pickUpStatus={item[7]}
+            key={item[3] + item[5]}
```
Comment (trev4ev) [inline src/components/Orders.js:53]: I made this change but just fyi if the key is just order number it is not unique for every row

**Review by trev4ev — CHANGES_REQUESTED** [review]
a couple of small changes! looks great though, I really like this solution

**Review by abaruah117 — APPROVED** [review]
lgtm
